# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b19e298366b111f94932f59a3d6c663cbcead3b19d72bd3a23e6cbecff2e1ec13cf5fbb124217260d7f704a54b307d8cc64347ec07105f24150dbd8c2ab0168

test:
  secret_key_base: d18ccdd0ab4ead995b5a971558c72c3e712fec6b51b4d713803a7075bc99a3b559b2c269ece0e53170d949dcf26e3c4623eb9a1a2901a860217c3e7249dc43a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
